// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXj2Fa1kkCUr4ilNsMlt3zpaWgDxDKvo',
    appId: '1:119441598732:web:df5ef1e19c5db7bc208129',
    messagingSenderId: '119441598732',
    projectId: 'chaty-70d82',
    authDomain: 'chaty-70d82.firebaseapp.com',
    storageBucket: 'chaty-70d82.appspot.com',
    measurementId: 'G-RFPHR3EJ3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIuWNsVrovhj753Qt8gwi0lZKLEqBXXQ',
    appId: '1:119441598732:android:ab66a46fec2a16a8208129',
    messagingSenderId: '119441598732',
    projectId: 'chaty-70d82',
    storageBucket: 'chaty-70d82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZxQcw3Qt0q4BRmp5FcKwJ1ZVSmR7RqA',
    appId: '1:119441598732:ios:f92857c20a98741c208129',
    messagingSenderId: '119441598732',
    projectId: 'chaty-70d82',
    storageBucket: 'chaty-70d82.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZxQcw3Qt0q4BRmp5FcKwJ1ZVSmR7RqA',
    appId: '1:119441598732:ios:706dfd9939a07585208129',
    messagingSenderId: '119441598732',
    projectId: 'chaty-70d82',
    storageBucket: 'chaty-70d82.appspot.com',
    iosBundleId: 'com.example.chatty.RunnerTests',
  );
}
